[package]
name = "mxp-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "mxp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module", "abi3-py38"] }
mxp = { path = "../mxp-protocol" }
bytes = "1.11"

[build-dependencies]
pyo3-build-config = "0.22"
